### ISSUE TITLE
Content Regionale Communities

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/GermanySmash#18]

**Comment by TaDavidID** [comment]
Discords:

Baden-Württemberg
https://discord.gg/ur4JzUT 

Bayern
https://discordapp.com/invite/tm2azmK

Berlin/Brandenburg
https://discordapp.com/invite/6r76SkA

Hamburg
https://discord.gg/GHS8Q5Y
Schleswig-Holstein
https://discordapp.com/invite/gED9Cbm
Mecklenburg-Vorpommern 
https://discord.gg/udNKmTK

Hessen 
https://discord.gg/gdhCQpzKb2 
Rheinland-Pfalz 
https://discord.gg/Q49Dbky
Saarland
https://discord.gg/phzRTMw

Niedersachsen und Bremen 
https://discordapp.com/invite/0X3myOFZHGCpW1G0

Nordrhein-Westfalen 
https://discordapp.com/invite/Aba35kP 

Sachsen, Sachsen-Anhalt und Thüringen
https://discord.gg/rBzNfVD

**Comment by TaDavidID** [comment]
Aufbau der Regional Seiten:

kurzer Text zur Region (optional / tbd)

Discord Server Embeds (1-3 Server pro Region)
![image](https://user-images.githubusercontent.com/59091824/148430151-13646f2f-72ae-4395-a597-f1e41f1323a8.png)

weitere Social Media Links, Twitter, Facebook etc.

Liste der upcoming Events für die Region gefiltert
![image](https://user-images.githubusercontent.com/59091824/148430297-574c4d83-f1b9-4415-8f29-9f4da0c61a10.png)

Link zum Powerranking der Region "Die besten Spieler aus dieser Region, laut dem aktuellsten Ranking)
http://www.germanysmash.de/rankings#region_hessen

TOs oder Kontaktpersonen aus der Region. 
Profile eingebettet oder stumpf Name, Discord und Twitter-Link.

**Comment by Yoshi20** [comment]
Das scheint der Trick zu sein um an die invite Daten von Discord zu kommen:
https://discord.com/api/invite/wA89CyA?with_counts=true

Icon:
https://cdn.discordapp.com/icons/283616018671206400/fb0999392838a309e5704df035d0dec8.png?size=128

Invite:
https://discord.com/invite/wA89CyA
