### ISSUE TITLE
UI Verbesserungen

### ISSUE THREAD

**Issue by TaDavidID** [Yoshi20/GermanySmash#23]
- [ ] 5 der Bundesland Wappen werden zu breit skaliert. Andere werden aber korrekt angezeigt. 
(Seitenverhältnis wird beibehalten und nicht in ein Quadrat gefüllt.) 
Falsch sind: Bremen, Mecklenburg-Vorpommern, NRW, Schleswig-Holstein, Sachen-Anhalt

- [x] Charakter Auswahl: Pyra bitte umbenennen in: "Pyra / Mythra" oder "Pyra and Mythra"

- [x] Die Sprachwechsel Buttons sind auf Windows nur Text, kannst du sie via SVG einbauen? 
https://commons.wikimedia.org/wiki/File:Flag_of_Germany.svg
https://commons.wikimedia.org/wiki/File:Flag_of_the_United_Kingdom.svg

- [x] Im Turnier-Kalender die Zeilen etwas größer machen möglich? 3 oder mehr Turniere am selben Tag sind nicht unüblich. Sollte Platz für 5,5 Turniere haben. 
![2022-01-07_18-41-15](https://user-images.githubusercontent.com/59091824/148593275-ccaf9a96-edff-4a6d-b16a-cbb0e1244890.png)

- [x] In der Turnier Liste, Beim Standort - ist es möglich die Stadt anzuzeigen anstatt der Strasse? Oder noch besser beides bzw die vollständige Adresse. 
Die Gebühr kann imo ausgeblendet werden in dieser Übersicht für mehr Platz. 
 
- [x] Ebenfalls in Turnier Liste: Statt dem “S1&2/22” Tag, lass einfach “2022” nutzen. Wie die Seasons mit/nach Covid eingeteilt werden steht eh noch nicht fest.

- [x] Im Main menu: Spieler -> Individuen würde ich umbenennen in "Liste"

**Comment by Yoshi20** [comment]
https://github.com/Yoshi20/GermanySmash/issues/27
