### ISSUE TITLE
About Seite 

### ISSUE THREAD

**Issue by TaDavidID** [Yoshi20/GermanySmash#25]
- [x] #Allgemein
**GermanySmash.de**
Diese Website wurde erstellt, um einen Überblick über die Super Smash Bros. Ultimate Szene in Deutschland zu geben und einen Einstiegspunkt für neue Spieler zu schaffen, damit sie gut in ihre lokale Smash-Community finden. 
Zusätzlich bietet die Webseite einen Turniermanager, der Turnierorganisatoren (TOs) ein einfaches Tool zum Verwalten von Turnieren bereitstellt.
Die Seite entstand mit der Vorlage von https://www.swisssmash.ch/ und wird primär betreut von:
Yomi (Admin und Entwickler)
TaDavidID (Koordination mit TOs)
_(hier die Admins einfach als Text, oder auch per TO Profil Einbindung)_

- [x] #Kalender
_ist super so._

- [x] #Power Ranking
_Tab ganz raus. Bedingungen stehen nicht fest & DE verwendet bisher immer ein manuelles Verfahren._ 

- [x] #Turniermanager
**Turnierveranstalter**
GermanySmash.de beinhaltet eine Webanwendung zum einfachen Erstellen und Verwalten von Smash Turnieren. 
Organisierst du selbst Turniere und möchtest den GermanySmash-Turniermanager nutzen? Schreib uns einfach eine Email.
**Bracket tool**
Aufgrund seinen kostenlosen, verzögerungsfreien und benutzerfreundlichen Turnierbäumen und API verwendet der GermanySmash-Turniermanager vorerst Challonge.
**Bracket Seeding**
Das anfängliche Seeding erfolgt, indem eine nach Fähigkeiten sortierte Spielerliste aus allen Daten auf germanysmash.de generiert wird:
player_skill = points/participations + wins/(wins+losses)*100 + participations + self_assessment/5 + tournament_experience/10
Das endgültige Seeding erfolgt manuell durch einen TO.

- [ ] #Resultate
**Resultate**
Nebst den Resultaten (Match Scores und Ranglistens) der internen Turniere des GermanySmash-Turnier-Managers kann germanysmash.de auch die Resultate aller anderen Turniere in Deutschland abrufen. Die einzige Bedingung ist, dass das Turnier auf braacket.com in der SSBU DE PRs Liga importiert wurde.
_Ranglisten System erstmal komplett raus, weil es nicht aktiv verwendet wird?_

- [x] #Seeding
_wurde in Turniermanager verschoben. Tab kann weg._ 

- [x] #Persönliche Daten
_komplett raus, weil das für DE 300 Seiten wären xD
Sollen die Leute die Details hier lesen: http://www.germanysmash.de/privacy_policy_

**Comment by Yoshi20** [comment]
Resultate würde ich drin lassen, einfach zum zeigen was und wie möglich wäre.
Eventuell lässt ich ja jemand engagiertes finden, der die Turniere auf braacket.com importiert.
