### ISSUE TITLE
3 Mii Chars separieren

### ISSUE THREAD

**Issue by TaDavidID** [Yoshi20/GermanySmash#31]
Weil dazu schon zwei Anfragen kamen, habe ich die fehlenden Grafiken für die drei Mii Icons nachgebaut. 
Habe SVGs und hier die 200x200px PNG Versionen

* [x] Mii Brawler 
* [x] Mii Gunner 
* [x] Mii Swordfighter

![Miis-02](https://user-images.githubusercontent.com/59091824/149038054-31f8a596-2971-409a-88e8-92c39de64c5d.png)
![Miis_Zeichenfläche 1](https://user-images.githubusercontent.com/59091824/149038051-ac79c9d7-9d1a-4c4c-ab84-0781d8a194a8.png)
![Miis-03](https://user-images.githubusercontent.com/59091824/149038056-597b9c9b-08da-4e58-b9d9-894bb5f49403.png)

**Comment by Yoshi20** [comment]
Sehr cool :)

Jetzt fehlt nur noch:
- charizard_200x200.png
- ivysaur_200x200.png
- mythra_200x200.png
- squirtle_200x200.png

Und nach male inkling wurde mal gefragt.

**Comment by TaDavidID** [comment]
Pokemon Trainer und Pyra-Mythra würde ich nicht separieren.
Die wenigsten spielen nur einen davon, das wechseln gehört zum Gameplan der Chars. 
Miis sind 3 getrennte Charactere und die meisten Mii-Mains spezialisieren sich auf einen davon.
